import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET() {
  const templates = [
    {
      id: 'shorts-viral',
      name: 'YouTube Shorts Viral Loop',
      category: 'Shorts & Vertical',
      format: 'Shorts',
      durationMinutes: 1,
      niche: 'Viral Facts & Trivia',
      visualStyle: 'Cinematic High-Contrast',
      voice: 'en-US-ChristopherNeural',
      description: 'High-retention 60-second fast-paced format with immediate pattern interrupt hook and dramatic soundscape.',
      promptStarter: '3 Psychological Tricks People Use Without Realizing It',
      badge: 'High Viral Retention',
    },
    {
      id: 'faceless-cash-cow',
      name: 'YouTube Faceless Automation',
      category: 'Long-Form Channel',
      format: 'YouTube',
      durationMinutes: 5,
      niche: 'Tech & Economy',
      visualStyle: 'Cyber Cyberpunk Tech',
      voice: 'en-US-GuyNeural',
      description: 'Structured 5-minute deep dive engineered for high RPM niches with curated B-roll footage and smooth transitions.',
      promptStarter: 'How Quantum Computers Will Break Global Encryption',
      badge: 'High RPM Niche',
    },
    {
      id: 'daily-tech-news',
      name: 'Daily Tech & AI Radar',
      category: 'News & Trends',
      format: 'YouTube',
      durationMinutes: 3,
      niche: 'AI & Future Technology',
      visualStyle: 'Documentary Minimalist',
      voice: 'en-US-ChristopherNeural',
      description: 'Concise daily news summary highlighting breaking tech breakthroughs, industry updates, and market impacts.',
      promptStarter: 'OpenAI and DeepMind Just Announced New Frontier AI Breakthroughs',
      badge: 'Daily Publishing',
    },
    {
      id: 'educational-deep-dive',
      name: 'Educational Explainer & Analysis',
      category: 'Education & Science',
      format: 'YouTube',
      durationMinutes: 5,
      niche: 'Science & History',
      visualStyle: 'Documentary Minimalist',
      voice: 'en-GB-SoniaNeural',
      description: 'Multi-chapter clinical breakdown explaining complex science, historical mysteries, or cognitive concepts simply.',
      promptStarter: 'The True Origin of Black Holes and Event Horizons',
      badge: 'Educational Evergreen',
    },
    {
      id: 'motivational-speech',
      name: 'High-Impact Motivational Voice',
      category: 'Self-Improvement',
      format: 'YouTube',
      durationMinutes: 3,
      niche: 'Mindset & Discipline',
      visualStyle: 'Gold Luxury Business',
      voice: 'en-US-GuyNeural',
      description: 'Inspiring, authoritative narration paired with cinematic high-contrast visuals designed for peak emotional engagement.',
      promptStarter: 'The Mindset Shift That Changes Everything in 6 Months',
      badge: 'High Engagement',
    },
    {
      id: 'health-vitality',
      name: 'Health & Longevity Science',
      category: 'Health & Wellness',
      format: 'YouTube',
      durationMinutes: 5,
      niche: 'Health & Nutrition',
      visualStyle: 'Emerald Nature Vitality',
      voice: 'en-US-JennyNeural',
      description: 'Evidence-based longevity protocols, nutrition breakdowns, and holistic morning routines.',
      promptStarter: '7 Morning Habits That Lower Cortisol and Increase Energy',
      badge: 'Evergreen Health',
    },
    {
      id: 'business-breakdown',
      name: 'Billion Dollar Business Case Study',
      category: 'Business & Finance',
      format: 'YouTube',
      durationMinutes: 8,
      niche: 'Business Strategy',
      visualStyle: 'Gold Luxury Business',
      voice: 'en-US-ChristopherNeural',
      description: '8-minute masterclass unpacking how world-class startups scale, monetize, and dominate markets.',
      promptStarter: 'How NVIDIA Built a Monopoly in Artificial Intelligence Hardware',
      badge: 'Masterclass Case Study',
    },
    {
      id: 'top-10-countdown',
      name: 'Top 10 Countdown Listicle',
      category: 'Entertainment',
      format: 'YouTube',
      durationMinutes: 5,
      niche: 'Curiosity & Travel',
      visualStyle: 'Cinematic High-Contrast',
      voice: 'en-US-ChristopherNeural',
      description: 'Fast-paced countdown format moving through 10 surprising items with individual scene titles.',
      promptStarter: 'Top 10 Most Isolated Places on Earth You Can Never Visit',
      badge: 'High Click-Through',
    },
    {
      id: 'saas-product-explainer',
      name: 'Software & SaaS Feature Showcase',
      category: 'Product & Tech',
      format: 'YouTube',
      durationMinutes: 2,
      niche: 'Productivity Software',
      visualStyle: 'Cyber Cyberpunk Tech',
      voice: 'en-US-JennyNeural',
      description: 'Clean product walkthrough explaining value proposition, core workflows, and end-user ROI.',
      promptStarter: 'How Modern Teams Automate Complex Video Workflows in 2026',
      badge: 'Product Marketing',
    },
  ];

  return NextResponse.json({ templates });
}
